version: "3.9"
services:
  mongo:
    container_name: table_mongo
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - './data_mongo:/data/db'

  elasticsearch:
    container_name: table_es
    image: elasticsearch:7.16.2
    environment:
      cluster.name: table
      node.name: table
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - './data_es:/usr/share/elasticsearch/data'